### ISSUE TITLE
[bug] SrsFastBuffer coredump

### ISSUE THREAD

**Issue by peckjerry** [simple-rtmp-server/srs#54]
几次碰到SrsFastBuffer coredump，怀疑grow函数实现逻辑异常。

srs: src/protocol/srs_rtmp_buffer.cpp:129: virtual void SrsFastBuffer::skip(int): Assertion `p + size > buffer' failed.

Program received signal SIGABRT, Aborted.
0x0000003932c328a5 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.107.el6.x86_64 libgcc-4.4.7-3.el6.x86_64 libstdc++-4.4.7-3.el6.x86_64
(gdb) bt
#0  0x0000003932c328a5 in raise () from /lib64/libc.so.6
#1  0x0000003932c34085 in abort () from /lib64/libc.so.6
#2  0x0000003932c2ba1e in __assert_fail_base () from /lib64/libc.so.6
#3  0x0000003932c2bae0 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000045a34a in SrsFastBuffer::skip (this=0x8ca6a0, size=-4) at src/protocol/srs_rtmp_buffer.cpp:129
#5  0x0000000000437b04 in SrsProtocol::read_message_header (this=0x8c81f0, chunk=0x8ce040, fmt=3 '\003') at src/protocol/srs_rtmp_stack.cpp:1791
#6  0x0000000000436c9b in SrsProtocol::recv_interlaced_message (this=0x8c81f0, pmsg=0x7ffff7f6dc40) at src/protocol/srs_rtmp_stack.cpp:1404
#7  0x000000000043486b in SrsProtocol::recv_message (this=0x8c81f0, pmsg=0x7ffff7f6dcc0) at src/protocol/srs_rtmp_stack.cpp:770
#8  0x000000000044bf08 in SrsRtmpServer::recv_message (this=0x8c5560, pmsg=0x7ffff7f6dcc0) at src/protocol/srs_rtmp_sdk.cpp:797
#9  0x000000000050fb35 in SrsRecvThread::cycle (this=0x7ffff7f378f8) at src/app/srs_app_recv_thread.cpp:88
#10 0x00000000004abd37 in SrsThread::thread_cycle (this=0x8eefd0) at src/app/srs_app_thread.cpp:187
#11 0x00000000004abf27 in SrsThread::thread_fun (arg=0x8eefd0) at src/app/srs_app_thread.cpp:225
#12 0x000000000052fcf6 in _st_thread_main () at sched.c:327
#13 0x0000000000530490 in st_thread_create (start=0x7ffff7f37700, arg=0x7ffff7f37e30, joinable=0, stk_size=9231600) at sched.c:591
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**Comment by peckjerry** [comment]
develop branch
